# Generated by Django 5.1.4 on 2026-07-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalclient',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='portalclient',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
