# Generated by Django 5.1.4 on 2026-07-03 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carné de Extranjería'), ('PAS', 'Pasaporte')], default='DNI', max_length=3)),
                ('document_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente espejo',
                'verbose_name_plural': 'Clientes espejo',
                'db_table': 'mirror_clients',
            },
        ),
        migrations.CreateModel(
            name='MirrorKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_idkardex', models.IntegerField(db_index=True, unique=True)),
                ('kardex', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fechaingreso', models.CharField(blank=True, default='', max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=255)),
                ('contrato', models.CharField(blank=True, default='', max_length=255)),
                ('contacto', models.CharField(blank=True, default='', max_length=255)),
                ('telecontacto', models.CharField(blank=True, max_length=30, null=True)),
                ('mailcontacto', models.CharField(blank=True, max_length=255, null=True)),
                ('fechacalificado', models.CharField(blank=True, max_length=20, null=True)),
                ('fechainstrumento', models.CharField(blank=True, max_length=20, null=True)),
                ('fechaconclusion', models.CharField(blank=True, max_length=20, null=True)),
                ('numescritura', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaescritura', models.CharField(blank=True, max_length=20, null=True)),
                ('numminuta', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('gestor', models.CharField(blank=True, max_length=255, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kardex espejo',
                'verbose_name_plural': 'Kardex espejo',
                'db_table': 'mirror_kardex',
                'ordering': ['-source_idkardex'],
            },
        ),
        migrations.CreateModel(
            name='MirrorKardexClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_links', to='tramites.mirrorclient')),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='tramites.mirrorkardex')),
            ],
            options={
                'verbose_name': 'Vínculo espejo cliente-kardex',
                'verbose_name_plural': 'Vínculos espejo cliente-kardex',
                'db_table': 'mirror_kardex_clients',
                'unique_together': {('kardex', 'client')},
            },
        ),
        migrations.AddField(
            model_name='mirrorkardex',
            name='clients',
            field=models.ManyToManyField(related_name='kardexes', through='tramites.MirrorKardexClient', to='tramites.mirrorclient'),
        ),
        migrations.CreateModel(
            name='MirrorKardexStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresado', models.BooleanField(default=False)),
                ('calificado', models.BooleanField(default=False)),
                ('calificado_observado', models.BooleanField(default=False)),
                ('calificado_digitacion', models.BooleanField(default=False)),
                ('generado_proyecto', models.BooleanField(default=False)),
                ('confrontado', models.BooleanField(default=False)),
                ('escriturado', models.BooleanField(default=False)),
                ('firmas_proceso', models.BooleanField(default=False)),
                ('firmas_concluidas', models.BooleanField(default=False)),
                ('partes_terminados', models.BooleanField(default=False)),
                ('presentado', models.BooleanField(default=False)),
                ('inscrito', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('kardex', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notarial_status', to='tramites.mirrorkardex')),
            ],
            options={
                'verbose_name': 'Estado notarial espejo',
                'verbose_name_plural': 'Estados notariales espejo',
                'db_table': 'mirror_kardex_status',
            },
        ),
        migrations.CreateModel(
            name='MirrorRRPPMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmovreg', models.IntegerField(db_index=True)),
                ('itemmov', models.IntegerField(default=0)),
                ('fechamov', models.CharField(blank=True, max_length=20, null=True)),
                ('vencimiento', models.CharField(blank=True, max_length=20, null=True)),
                ('titulorp', models.CharField(blank=True, max_length=100, null=True)),
                ('tramite', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_abrev', models.CharField(blank=True, max_length=50, null=True)),
                ('sede', models.CharField(blank=True, max_length=255, null=True)),
                ('seccion', models.CharField(blank=True, max_length=255, null=True)),
                ('encargado', models.CharField(blank=True, max_length=255, null=True)),
                ('importee', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_partida', models.CharField(blank=True, max_length=100, null=True)),
                ('asiento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inscripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('observa', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('kardex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rrpp_movements', to='tramites.mirrorkardex')),
            ],
            options={
                'verbose_name': 'Movimiento RRPP espejo',
                'verbose_name_plural': 'Movimientos RRPP espejo',
                'db_table': 'mirror_rrpp_movements',
                'ordering': ['idmovreg', 'itemmov'],
                'unique_together': {('idmovreg', 'itemmov')},
            },
        ),
    ]
